function(cellerator_write_resource_manifest output root)
  file(GLOB_RECURSE _files RELATIVE "${root}" "${root}/*")
  list(SORT _files)
  file(WRITE "${output}" "format=cellerator-resource-manifest-v1\nceir=1\nprofile=1\nschema=1\n")
  foreach(_path IN LISTS _files)
    if(NOT IS_DIRECTORY "${root}/${_path}")
      file(SHA256 "${root}/${_path}" _sha256)
      file(APPEND "${output}" "${_sha256}  ${_path}\n")
    endif()
  endforeach()
endfunction()
