include(CMakeFindDependencyMacro)
set(Cellerator_VERSION "1.0.0")
set(Cellerator_CEIR_VERSION 1)
set(Cellerator_PROFILE_VERSION 1)
set(Cellerator_HAS_COMPILER TRUE)
set(Cellerator_HAS_RUNTIME TRUE)
set(Cellerator_HAS_CUDA_BACKEND TRUE)
set(_cellerator_components Compiler Runtime BackendCUDA ProviderSDK)
foreach(_component IN LISTS _cellerator_components)
  if(NOT TARGET Cellerator::${_component})
    add_library(Cellerator::${_component} INTERFACE IMPORTED)
  endif()
endforeach()
unset(_cellerator_components)
