#include <Cellerator/compiler/profile/implement_streaming_profile_builders_v1.hh>
#include <cmath>
#include <cstring>
namespace cellerator::compiler::profile::v1 {
std::uint64_t streaming_profile_workspace_bytes_v1(const streaming_profile_policy_v1&p) noexcept{return 8ull*p.histogram_bins+8ull*p.top_l+8ull*p.sketch_slots+(p.exact_small_mode?8ull*p.top_l:0ull);}
streaming_profile_status_v1 initialize_streaming_profile_builder_v1(const streaming_profile_policy_v1&p,streaming_profile_workspace_v1 w,streaming_profile_builder_v1*out) noexcept{auto n=streaming_profile_workspace_bytes_v1(p);if(!out||!p.histogram_bins||!p.sketch_slots)return streaming_profile_status_v1::invalid_argument;if(n>p.memory_budget_bytes||n>w.capacity_bytes||!w.histogram||!w.top_values||!w.sketch||(p.exact_small_mode&&!w.exact_values))return streaming_profile_status_v1::insufficient_budget;std::memset(w.histogram,0,8*p.histogram_bins);std::memset(w.top_values,0,8*p.top_l);std::memset(w.sketch,0,8*p.sketch_slots);*out={p,w};return streaming_profile_status_v1::ok;}
streaming_profile_status_v1 update_streaming_profile_builder_v1(streaming_profile_builder_v1*b,const double*v,std::uint64_t n) noexcept{if(!b||(n&&!v))return streaming_profile_status_v1::invalid_argument;for(std::uint64_t i=0;i<n;++i){if(!std::isfinite(v[i]))continue;if(!b->count)b->minimum=b->maximum=v[i];b->minimum=v[i]<b->minimum?v[i]:b->minimum;b->maximum=v[i]>b->maximum?v[i]:b->maximum;++b->count;double d=v[i]-b->mean;b->mean+=d/b->count;b->m2+=d*(v[i]-b->mean);auto h=static_cast<std::uint64_t>(std::abs(v[i])*11400714819323198485ull);b->workspace.sketch[h%b->policy.sketch_slots]|=1ull<<(h%63u);b->workspace.histogram[h%b->policy.histogram_bins]++;for(std::uint32_t j=0;j<b->policy.top_l;++j)if(std::abs(v[i])>std::abs(b->workspace.top_values[j])){for(std::uint32_t k=b->policy.top_l-1;k>j;--k)b->workspace.top_values[k]=b->workspace.top_values[k-1];b->workspace.top_values[j]=v[i];break;}if(b->policy.exact_small_mode){if(b->exact_count>=b->policy.top_l)return streaming_profile_status_v1::capacity_exceeded;b->workspace.exact_values[b->exact_count++]=v[i];}}return streaming_profile_status_v1::ok;}
streaming_profile_status_v1 finalize_streaming_profile_builder_v1(const streaming_profile_builder_v1&b,streaming_profile_result_v1*r) noexcept{if(!r)return streaming_profile_status_v1::invalid_argument;std::uint64_t bits=0;for(std::uint32_t i=0;i<b.policy.sketch_slots;++i)bits+=__builtin_popcountll(b.workspace.sketch[i]);*r={b.count,streaming_profile_workspace_bytes_v1(b.policy),b.mean,b.count?b.m2/b.count:0.0,static_cast<double>(bits),1.0/std::sqrt(static_cast<double>(b.policy.sketch_slots))};return streaming_profile_status_v1::ok;}
streaming_profile_status_v1 count_scan_fill_offsets_v1(const std::uint32_t*c,std::uint32_t n,std::uint64_t*o,std::uint32_t cap,std::uint64_t*total) noexcept{if(!c||!o||!total||cap<n+1u)return streaming_profile_status_v1::invalid_argument;o[0]=0;for(std::uint32_t i=0;i<n;++i)o[i+1]=o[i]+c[i];*total=o[n];return streaming_profile_status_v1::ok;}
}  // namespace cellerator::compiler::profile::v1
