#include <filesystem>
#include <fstream>
#include <iostream>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace {

std::string read_text(const fs::path& path) {
    std::ifstream stream(path);
    if (!stream) {
        throw std::runtime_error("cannot read " + path.string());
    }
    std::ostringstream text;
    text << stream.rdbuf();
    return text.str();
}

void require(bool condition, const std::string& message) {
    if (!condition) {
        throw std::runtime_error(message);
    }
}

std::size_t count_files(const fs::path& root) {
    std::size_t count = 0;
    for (const auto& entry : fs::recursive_directory_iterator(root)) {
        if (entry.is_regular_file()) {
            ++count;
        }
    }
    return count;
}

}  // namespace

int main(int argc, char** argv) {
    try {
        require(argc == 4, "usage: test RECEIPT CELLERATOR_ROOT CELLSHARD_ROOT");
        const std::string receipt = read_text(argv[1]);
        const fs::path cellerator_root = argv[2];
        const fs::path cellshard_root = argv[3];

        const std::string license = read_text(cellshard_root / "LICENSE");
        require(license.find("Apache License") != std::string::npos,
                "CellShard license is not identified");
        require(license.find("Version 2.0") != std::string::npos,
                "CellShard Apache license version is not identified");
        for (const char* name : {"LICENSE", "COPYING", "NOTICE"}) {
            require(!fs::exists(cellerator_root / name),
                    std::string("receipt must be refreshed: destination now has ") + name);
        }

        require(count_files(cellshard_root / "include/CellShard/compiler") == 222,
                "compiler header inventory drifted");
        require(count_files(cellshard_root / "src/compiler") == 19,
                "compiler source inventory drifted");
        require(count_files(cellshard_root / "tests/jbc") == 328,
                "JBC test inventory drifted");
        require(count_files(cellshard_root / "bench/jbc") == 6,
                "JBC benchmark inventory drifted");

        std::size_t source_notice_count = 0;
        for (const fs::path& audit_root : {
                 cellshard_root / "include/CellShard/compiler",
                 cellshard_root / "src/compiler",
                 cellshard_root / "tests/jbc",
                 cellshard_root / "bench/jbc"}) {
            for (const auto& entry : fs::recursive_directory_iterator(audit_root)) {
                if (!entry.is_regular_file()) {
                    continue;
                }
                const std::string source = read_text(entry.path());
                if (source.find("SPDX-License-Identifier") != std::string::npos
                    || source.find("Copyright (c)") != std::string::npos) {
                    ++source_notice_count;
                }
                for (const char* marker : {
                         "DO NOT EDIT", "auto-generated", "autogenerated", "generated by",
                         "configure_file(", "file(GENERATE"}) {
                    require(source.find(marker) == std::string::npos,
                            "unclassified generated marker in " + entry.path().string());
                }
            }
        }
        require(source_notice_count == 0, "source-level license notice inventory drifted");

        std::size_t quoted_package_includes = 0;
        std::size_t external_dependency_headers = 0;
        const fs::path compiler_headers = cellshard_root / "include/CellShard/compiler";
        for (const auto& entry : fs::recursive_directory_iterator(compiler_headers)) {
            if (!entry.is_regular_file()) {
                continue;
            }
            const std::string source = read_text(entry.path());
            if (source.find("#include \"CellShard/") != std::string::npos) {
                ++quoted_package_includes;
            }
            if (source.find("#include <CellShard/domain.hh>") != std::string::npos
                || source.find("#include <CellShard/identity.hh>") != std::string::npos
                || source.find("#include <CellShard/identity/digest.hh>") != std::string::npos
                || source.find("#include <CellShard/identity/strong_id.hh>") != std::string::npos
                || source.find("#include <CellShard/artifact/image.hh>") != std::string::npos) {
                ++external_dependency_headers;
            }
        }
        require(quoted_package_includes == 22,
                "quoted CellShard include inventory drifted");
        require(external_dependency_headers == 14,
                "external compiler dependency inventory drifted");

        const std::string embedded = read_text(cellshard_root /
            "tests/jbc/validation/embedded_consumer/CMakeLists.txt");
        require(embedded.find("CELLSHARD_SOURCE_DIR") != std::string::npos,
                "embedded consumer root assumption missing");
        require(embedded.find("CELLSHARD_CELLERATOR_SOURCE_DIR") != std::string::npos,
                "embedded consumer Cellerator root assumption missing");
        require(embedded.find("add_subdirectory") != std::string::npos,
                "embedded consumer source-tree assumption missing");

        const std::size_t begin = receipt.find("<!-- EXCEPTIONS-BEGIN -->");
        const std::size_t end = receipt.find("<!-- EXCEPTIONS-END -->");
        require(begin < end, "missing exception table markers");
        const std::string exceptions = receipt.substr(begin, end - begin);
        for (int number = 1; number <= 12; ++number) {
            std::ostringstream id;
            id << "| JBC-X";
            if (number < 10) {
                id << '0';
            }
            id << number << " |";
            const std::size_t first = exceptions.find(id.str());
            require(first != std::string::npos, "missing exception " + id.str());
            require(exceptions.find(id.str(), first + id.str().size()) == std::string::npos,
                    "duplicate exception " + id.str());
        }
        require(receipt.find("zero permitted silent generated-file copies")
                    != std::string::npos,
                "silent generated-file copy rule missing");
        require(receipt.find("fails closed") != std::string::npos,
                "pre-copy gate is not fail-closed");

        std::cout << "validated 12 migration exceptions and zero silent generated copies\n";
        return 0;
    } catch (const std::exception& error) {
        std::cerr << error.what() << '\n';
        return 1;
    }
}
