#include <Cellerator/compiler/backend/nvcc/implement_cuda_source_emission_v1.hh>

#include <algorithm>
#include <set>
#include <utility>

namespace cellerator::compiler::backend::nvcc::v1 {
namespace {
void set_status(emission_status* out, emission_status value) noexcept {
    if (out != nullptr) *out = value;
}
}  // namespace

std::optional<emitted_cuda_source> emit_cuda_source(
    const realized_cuda_module& module, emission_status* status) noexcept {
    if (module.generated_path.empty() || module.cellerator_path.empty()) {
        set_status(status, emission_status::invalid_module);
        return std::nullopt;
    }
    auto entities = module.entities;
    std::sort(entities.begin(), entities.end(), [](const auto& left, const auto& right) {
        if (left.kind != right.kind) return left.kind < right.kind;
        return left.stable_name < right.stable_name;
    });
    std::set<std::string> names;
    for (const auto& entity : entities) {
        if (entity.kind < cuda_entity_kind::constant ||
            entity.kind > cuda_entity_kind::runtime_binding ||
            entity.stable_name.empty() || entity.declaration.empty() ||
            entity.cellerator_line == 0u) {
            set_status(status, emission_status::invalid_entity);
            return std::nullopt;
        }
        if (!names.insert(entity.stable_name).second) {
            set_status(status, emission_status::duplicate_entity);
            return std::nullopt;
        }
    }
    auto includes = module.includes;
    std::sort(includes.begin(), includes.end());
    includes.erase(std::unique(includes.begin(), includes.end()), includes.end());
    emitted_cuda_source result;
    result.text = "// Generated by Cellerator; NVCC must not parse .cell source.\n";
    for (const auto& include : includes) result.text += "#include <" + include + ">\n";
    result.text += "\n";
    std::uint32_t line = static_cast<std::uint32_t>(
        std::count(result.text.begin(), result.text.end(), '\n')) + 1u;
    for (const auto& entity : entities) {
        result.source_map.push_back(
            {module.generated_path, module.cellerator_path, line, entity.cellerator_line});
        result.text += entity.declaration;
        if (result.text.back() != '\n') result.text += '\n';
        result.text += '\n';
        line = static_cast<std::uint32_t>(
            std::count(result.text.begin(), result.text.end(), '\n')) + 1u;
    }
    set_status(status, emission_status::ok);
    return result;
}

}  // namespace cellerator::compiler::backend::nvcc::v1
