# Selectable build projection of actual CE owners. This is not a runtime registry.
include(GNUInstallDirs)
include(CMakePackageConfigHelpers)
get_filename_component(CE_SUBSTRATE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
option(CELLERATOR_SUBSTRATE_REQUIRE_INTEGRATED "Require all merged IS1 leaf sources" OFF)
option(CELLERATOR_SUBSTRATE_ENABLE_SM70 "Build the existing device-linear CUDA 12.x provider" OFF)
set(CELLERATOR_SUBSTRATE_COMPONENTS "host_operation_contracts;relation_semantics;native_numeric;executable_program;indexed_incidence;cellpack;moonshot_effects;moonshot_mechanisms;moonshot_learning" CACHE STRING "Explicit host component roots; dependencies are selected automatically")
if(CELLERATOR_SUBSTRATE_REQUIRE_INTEGRATED)
  foreach(path include/Cellerator/state/structured_state.hh include/Cellerator/packing/strategy.hh
      include/Cellerator/math/matrix/patch.hh include/Cellerator/math/process/ports.hh
      include/Cellerator/math/effects/affine.hh include/Cellerator/execution/prepared_host_sweep.hh)
    if(NOT EXISTS "${CE_SUBSTRATE_ROOT}/${path}")
      message(FATAL_ERROR "IS1 integration prerequisite missing: ${path}; merge accepted leaves first")
    endif()
  endforeach()
  list(APPEND CELLERATOR_SUBSTRATE_COMPONENTS structured_state packing_strategy matrix_patch private_ports effects prepared_host)
endif()
set(_ce_deps_operation_schema "")
set(_ce_deps_host_operation_contracts operation_schema)
set(_ce_deps_relation_semantics "")
set(_ce_deps_native_numeric relation_semantics)
set(_ce_deps_executable_program "")
set(_ce_deps_indexed_incidence host_operation_contracts)
set(_ce_deps_cellpack "")
set(_ce_deps_local_differential native_numeric executable_program operation_schema)
set(_ce_deps_moonshot_effects "")
set(_ce_deps_moonshot_mechanisms "")
set(_ce_deps_moonshot_learning "")
set(_ce_deps_structured_state host_operation_contracts)
set(_ce_deps_packing_strategy native_numeric indexed_incidence cellpack)
set(_ce_deps_matrix_patch host_operation_contracts)
set(_ce_deps_private_ports host_operation_contracts)
set(_ce_deps_effects host_operation_contracts moonshot_effects moonshot_mechanisms)
set(_ce_deps_prepared_host local_differential)
set(_ce_deps_packing_strategies packing_strategy)
set(_ce_deps_frontier effects native_numeric)
set(_ce_deps_response prepared_host)
set(_ce_deps_adaptive structured_state)
set(_ce_deps_native_numeric_sm70 native_numeric)
set(_ce_known operation_schema host_operation_contracts relation_semantics native_numeric executable_program indexed_incidence
  cellpack local_differential moonshot_effects moonshot_mechanisms moonshot_learning structured_state
  packing_strategy matrix_patch private_ports effects prepared_host packing_strategies frontier response adaptive native_numeric_sm70)
if(CELLERATOR_SUBSTRATE_ENABLE_SM70)
  list(APPEND CELLERATOR_SUBSTRATE_COMPONENTS native_numeric_sm70)
endif()
set(_ce_selected "")
function(_ce_select component)
  if(NOT component IN_LIST _ce_known)
    message(FATAL_ERROR "Unknown Cellerator substrate component: ${component}")
  endif()
  get_property(selected GLOBAL PROPERTY CE_SUBSTRATE_SELECTED)
  if(component IN_LIST selected)
    return()
  endif()
  foreach(dependency IN LISTS _ce_deps_${component})
    _ce_select(${dependency})
  endforeach()
  set_property(GLOBAL APPEND PROPERTY CE_SUBSTRATE_SELECTED ${component})
endfunction()
set_property(GLOBAL PROPERTY CE_SUBSTRATE_SELECTED "")
foreach(component IN LISTS CELLERATOR_SUBSTRATE_COMPONENTS)
  _ce_select(${component})
endforeach()
get_property(_ce_selected GLOBAL PROPERTY CE_SUBSTRATE_SELECTED)

if(native_numeric_sm70 IN_LIST _ce_selected)
  if(NOT CELLERATOR_SUBSTRATE_ENABLE_SM70)
    message(FATAL_ERROR "native_numeric_sm70 requires CELLERATOR_SUBSTRATE_ENABLE_SM70=ON")
  endif()
  # Explicit qualification toolchain: no silent CUDA 13 or architecture upgrade.
  set(CMAKE_CUDA_ARCHITECTURES 70 CACHE STRING "Substrate CUDA architecture" FORCE)
  enable_language(CUDA)
  find_package(CUDAToolkit 12 REQUIRED)
  if(CUDAToolkit_VERSION VERSION_GREATER_EQUAL 13 OR CMAKE_CUDA_COMPILER_VERSION VERSION_GREATER_EQUAL 13)
    message(FATAL_ERROR "Substrate SM70 requires CUDA 12.x")
  endif()
endif()
if(local_differential IN_LIST _ce_selected)
  find_path(CE_SUBSTRATE_CUDA_HEADERS cuda_runtime_api.h HINTS
    /opt/nvidia/hpc_sdk/Linux_x86_64/26.1/cuda/12.9/include REQUIRED)
endif()

function(_ce_owner name)
  cmake_parse_arguments(ARG "" "CAPABILITIES" "SOURCES;INCLUDES" ${ARGN})
  if(ARG_SOURCES)
    set(sources)
    foreach(source IN LISTS ARG_SOURCES)
      list(APPEND sources "${CE_SUBSTRATE_ROOT}/${source}")
    endforeach()
    add_library(cellerator_substrate_${name} STATIC ${sources})
    set(scope PUBLIC)
  else()
    add_library(cellerator_substrate_${name} INTERFACE)
    set(scope INTERFACE)
  endif()
  set(target cellerator_substrate_${name})
  add_library(Cellerator::${name} ALIAS ${target})
  set_target_properties(${target} PROPERTIES EXPORT_NAME ${name}
    CELLERATOR_CAPABILITIES "${ARG_CAPABILITIES}" EXPORT_PROPERTIES CELLERATOR_CAPABILITIES)
  target_compile_features(${target} ${scope} cxx_std_20)
  target_include_directories(${target} ${scope}
    $<BUILD_INTERFACE:${CE_SUBSTRATE_ROOT}/include> $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
  foreach(path IN LISTS ARG_INCLUDES)
    target_include_directories(${target} ${scope} $<BUILD_INTERFACE:${CE_SUBSTRATE_ROOT}/${path}>)
  endforeach()
  foreach(dependency IN LISTS _ce_deps_${name})
    target_link_libraries(${target} ${scope} Cellerator::${dependency})
  endforeach()
  if(ARG_SOURCES AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(${target} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-fno-fast-math;-ffp-contract=off>)
  endif()
  install(TARGETS ${target} EXPORT Cellerator_${name} ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
  install(EXPORT Cellerator_${name} FILE Cellerator_${name}Targets.cmake
    NAMESPACE Cellerator:: DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Cellerator)
endfunction()
foreach(component IN LISTS _ce_selected)
  if(component STREQUAL operation_schema)
    _ce_owner(${component} CAPABILITIES "native_v2_contract_validation" SOURCES src/compute/operation/operation_core_v2/schema.cc)
  elseif(component STREQUAL host_operation_contracts)
    _ce_owner(${component} CAPABILITIES "native_contracts")
  elseif(component STREQUAL relation_semantics)
    _ce_owner(${component} CAPABILITIES "host_relation_contracts" SOURCES src/compute/operation/relation_semantics.cc)
  elseif(component STREQUAL native_numeric)
    _ce_owner(${component} CAPABILITIES "host_relation,host_f32_f64_local" SOURCES
      src/compute/operation/native_numeric/host_relation.cc src/compute/operation/native_numeric/local_arithmetic.cc)
  elseif(component STREQUAL executable_program)
    _ce_owner(${component} CAPABILITIES "fixed_stage_graph" SOURCES src/execution/program/program_v2.cc)
  elseif(component STREQUAL indexed_incidence)
    _ce_owner(${component} CAPABILITIES "host_ordered_incidence,no_evaluators,no_device_training" SOURCES
      src/compute/operation/indexed_mechanism/incidence.cc)
  elseif(component STREQUAL cellpack)
    _ce_owner(${component} CAPABILITIES "host_geometry_planner,evaluator" SOURCES src/geometry/planner.cc src/geometry/evaluator.cc)
  elseif(component STREQUAL local_differential)
    _ce_owner(${component} CAPABILITIES "host_f32_f64_forward_jvp_vjp,cuda_headers_required" SOURCES
      src/compute/operation/differential/local_arithmetic.cc)
    target_include_directories(cellerator_substrate_${component} SYSTEM PRIVATE "${CE_SUBSTRATE_CUDA_HEADERS}")
  elseif(component STREQUAL moonshot_effects)
    _ce_owner(${component} CAPABILITIES "experimental_host_effects" INCLUDES
      experiments/baseplane_moonshot/include experiments/baseplane_moonshot/families/effects/include)
  elseif(component STREQUAL moonshot_mechanisms)
    _ce_owner(${component} CAPABILITIES "experimental_host_mechanisms" INCLUDES
      experiments/baseplane_moonshot/families/mechanisms/include)
  elseif(component STREQUAL moonshot_learning)
    _ce_owner(${component} CAPABILITIES "experimental_host_learning" INCLUDES experiments/baseplane_moonshot/families/learning)
  elseif(component STREQUAL structured_state)
    _ce_owner(${component} CAPABILITIES "host_borrowed_scalar_ragged_state" SOURCES src/state/structured_state.cc)
  elseif(component STREQUAL packing_strategy)
    _ce_owner(${component} CAPABILITIES "cold_host_identity_supplied_cellpack" SOURCES src/packing/core/strategy.cc)
  elseif(component STREQUAL matrix_patch)
    _ce_owner(${component} CAPABILITIES "host_f32_patch_forward_vjp_jvp" SOURCES
      src/math/matrix/patch.cc experiments/moonshot-parallel-v1/diff/patch/native.cc)
  elseif(component STREQUAL private_ports)
    _ce_owner(${component} CAPABILITIES "host_f32_private_transport_forward_vjp_jvp" SOURCES
      src/math/process/ports.cc experiments/moonshot-parallel-v1/diff/ports/transport.cc)
  elseif(component STREQUAL effects)
    _ce_owner(${component} CAPABILITIES "host_affine_hybrid_effects")
  elseif(component STREQUAL prepared_host)
    _ce_owner(${component} CAPABILITIES "host_f32_f64_prepared_scaled_tanh")
  elseif(component STREQUAL packing_strategies)
    _ce_owner(${component} CAPABILITIES "host_order_preserving_placement" SOURCES src/packing/strategies/placement.cc)
  elseif(component STREQUAL frontier)
    _ce_owner(${component} CAPABILITIES "finite_host_f64_quadratic_solve_ports_multilevel" SOURCES src/math/frontier/operators.cc)
  elseif(component STREQUAL response)
    _ce_owner(${component} CAPABILITIES "host_requested_f32_f64_scaled_tanh" SOURCES src/math/response/requested.cc)
  elseif(component STREQUAL adaptive)
    _ce_owner(${component} CAPABILITIES "host_delta_ledger_serialized_publication" SOURCES src/math/adaptive/reuse.cc)
  elseif(component STREQUAL native_numeric_sm70)
    _ce_owner(${component} CAPABILITIES "cuda12_sm70_device_linear" SOURCES src/compute/operation/native_numeric/device_linear.cu)
    target_link_libraries(cellerator_substrate_${component} PUBLIC CUDA::cudart)
    set_target_properties(cellerator_substrate_${component} PROPERTIES CUDA_STANDARD 20 CUDA_STANDARD_REQUIRED YES)
  endif()
endforeach()
# Public native headers are installed intact. Header presence is not a claim that
# every declared GPU/adapter symbol is linked by a selected host component.
install(DIRECTORY "${CE_SUBSTRATE_ROOT}/include/Cellerator" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
if(moonshot_effects IN_LIST _ce_selected)
  install(FILES "${CE_SUBSTRATE_ROOT}/experiments/baseplane_moonshot/include/ce_moon/reference.hpp"
    "${CE_SUBSTRATE_ROOT}/experiments/baseplane_moonshot/families/effects/include/ce_moon/effects.hpp"
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ce_moon)
endif()
if(moonshot_mechanisms IN_LIST _ce_selected)
  install(FILES "${CE_SUBSTRATE_ROOT}/experiments/baseplane_moonshot/families/mechanisms/include/ce_moon/mechanisms.hpp"
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ce_moon)
endif()
if(moonshot_learning IN_LIST _ce_selected)
  install(FILES "${CE_SUBSTRATE_ROOT}/experiments/baseplane_moonshot/families/learning/learning.hpp"
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
endif()
set(CE_SUBSTRATE_DEPENDENCY_TABLE "")
foreach(component IN LISTS _ce_known)
  string(APPEND CE_SUBSTRATE_DEPENDENCY_TABLE "set(_ce_deps_${component} \"${_ce_deps_${component}}\")\n")
endforeach()
find_package(Git QUIET)
set(CE_SUBSTRATE_SOURCE_REVISION "unversioned")
if(GIT_FOUND)
  execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
    WORKING_DIRECTORY "${CE_SUBSTRATE_ROOT}" OUTPUT_VARIABLE CE_SUBSTRATE_SOURCE_REVISION
    OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()
configure_package_config_file("${CMAKE_CURRENT_LIST_DIR}/CelleratorConfig.cmake.in"
  "${CMAKE_CURRENT_BINARY_DIR}/CelleratorConfig.cmake" INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Cellerator)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/CelleratorConfig.cmake" DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Cellerator)
