cmake_minimum_required(VERSION 3.20)
project(CelleratorNF1ExternalCustomConsumer LANGUAGES CXX CUDA)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CUDA_STANDARD 20)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)
find_package(Cellerator CONFIG REQUIRED COMPONENTS native_foundation)
add_executable(ce_nf1_installed_external_custom_consumer ../external_custom_operation.cu)
target_link_libraries(ce_nf1_installed_external_custom_consumer PRIVATE Cellerator::native_foundation CUDA::cudart)
enable_testing()
add_test(NAME ce_nf1_installed_external_custom_consumer COMMAND ce_nf1_installed_external_custom_consumer)
