#include <Cellerator/compiler/ir/realization/implement_realization_ir_text_parser_printer_v1.hh>
#include <iomanip>
#include <sstream>
namespace cellerator::compiler::ir::realization::v1 {namespace{
std::string hex(const std::string&s){std::ostringstream o;o<<std::hex<<std::setfill('0');for(unsigned char c:s)o<<std::setw(2)<<static_cast<unsigned>(c);return o.str();}
bool unhex(const std::string&s,std::string*out){if(s.size()%2)return false;out->clear();for(std::size_t i=0;i<s.size();i+=2){unsigned v=0;std::istringstream in(s.substr(i,2));in>>std::hex>>v;if(!in||v>255)return false;out->push_back(static_cast<char>(v));}return true;}}
std::string print_realization_text_v1(const realization_text_document_v1&d){std::ostringstream o;o<<"realization.v1 "<<d.module.high<<':'<<d.module.low<<'\n';for(const auto&r:d.records)o<<r.kind<<' '<<r.identity.high<<':'<<r.identity.low<<' '<<(r.payload.empty()?"-":hex(r.payload))<<'\n';return o.str();}
std::optional<realization_text_document_v1> parse_realization_text_v1(const std::string&t,std::string*e){std::istringstream in(t);std::string version,id;if(!(in>>version>>id)||version!="realization.v1"){if(e)*e="invalid realization header";return std::nullopt;}auto colon=id.find(':');realization_text_document_v1 d;if(colon==std::string::npos){if(e)*e="invalid module identity";return std::nullopt;}try{d.module={std::stoull(id.substr(0,colon)),std::stoull(id.substr(colon+1))};}catch(...){if(e)*e="invalid module identity";return std::nullopt;}std::string line;std::getline(in,line);while(std::getline(in,line)){if(line.empty())continue;std::istringstream row(line);realization_text_record_v1 r;std::string encoded;if(!(row>>r.kind>>id>>encoded)||row.rdbuf()->in_avail()!=0){if(e)*e="invalid realization record";return std::nullopt;}colon=id.find(':');if(colon==std::string::npos){if(e)*e="invalid record identity";return std::nullopt;}try{r.identity={std::stoull(id.substr(0,colon)),std::stoull(id.substr(colon+1))};}catch(...){if(e)*e="invalid record identity";return std::nullopt;}if(encoded=="-")r.payload.clear();else if(!unhex(encoded,&r.payload)){if(e)*e="invalid payload encoding";return std::nullopt;}d.records.push_back(std::move(r));}if(e)e->clear();return d;}
bool equivalent_realization_text_v1(const realization_text_document_v1&a,const realization_text_document_v1&b)noexcept{if(!(a.module==b.module)||a.records.size()!=b.records.size())return false;for(std::size_t i=0;i<a.records.size();++i)if(a.records[i].kind!=b.records[i].kind||!(a.records[i].identity==b.records[i].identity)||a.records[i].payload!=b.records[i].payload)return false;return true;}
} // namespace cellerator::compiler::ir::realization::v1
