#include <Cellerator/compiler/ir/realization/implement_symbolic_runtime_bindings_v1.hh>
#include <algorithm>
#include <cstring>
#include <set>
#include <tuple>
namespace cellerator::compiler::ir::realization::v1 {namespace{using key=std::tuple<std::uint64_t,std::uint64_t>;key k(stable_identity_v1 i){return{i.high,i.low};}bool pow2(std::uint64_t v){return v&&(v&(v-1))==0;}}
symbolic_binding_status_v1 validate_symbolic_binding_table_v1(const symbolic_binding_table_v1&t)noexcept{if(!valid(t.identity))return symbolic_binding_status_v1::invalid_identity;std::set<key>ids;for(const auto&s:t.slots){if(!valid(s.identity))return symbolic_binding_status_v1::invalid_identity;if(!ids.insert(k(s.identity)).second)return symbolic_binding_status_v1::duplicate_slot;if(!pow2(s.alignment))return symbolic_binding_status_v1::invalid_alignment;}return symbolic_binding_status_v1::valid;}
symbolic_binding_status_v1 bind_symbolic_runtime_v1(const symbolic_binding_table_v1&t,const std::vector<live_runtime_binding_v1>&live)noexcept{auto s=validate_symbolic_binding_table_v1(t);if(s!=symbolic_binding_status_v1::valid)return s;if(live.size()!=t.slots.size())return symbolic_binding_status_v1::missing_live_binding;std::set<key>seen;for(const auto&b:live){auto it=std::find_if(t.slots.begin(),t.slots.end(),[&](const auto&x){return x.identity==b.slot;});if(it==t.slots.end())return symbolic_binding_status_v1::unexpected_live_binding;if(!seen.insert(k(b.slot)).second)return symbolic_binding_status_v1::unexpected_live_binding;bool stream=it->kind==binding_slot_kind_v1::stream;bool token=it->kind==binding_slot_kind_v1::handle||it->kind==binding_slot_kind_v1::event||it->kind==binding_slot_kind_v1::lease;if((stream&&!b.stream)||(token&&!b.runtime_token)||(!stream&&!token&&!b.address))return symbolic_binding_status_v1::null_live_resource;}return symbolic_binding_status_v1::valid;}
std::vector<std::uint8_t> serialize_symbolic_bindings_v1(const symbolic_binding_table_v1&t){std::vector<std::uint8_t>o(sizeof(t.identity)+t.slots.size()*sizeof(symbolic_binding_slot_v1));std::memcpy(o.data(),&t.identity,sizeof(t.identity));if(!t.slots.empty())std::memcpy(o.data()+sizeof(t.identity),t.slots.data(),t.slots.size()*sizeof(symbolic_binding_slot_v1));return o;}
} // namespace cellerator::compiler::ir::realization::v1
