include_guard(GLOBAL)

set(CELLERATOR_COMPILER_VERSION "1.0.0" CACHE STRING "Compiler version")
set(CELLERATOR_LANGUAGE_REVISION "1" CACHE STRING "Source language revision")
set(CELLERATOR_CEIR_REVISION "1" CACHE STRING "CEIR revision")

function(cellerator_generate_compiler_build_header output)
    file(GENERATE OUTPUT "${output}" CONTENT
"#pragma once
#define CELLERATOR_COMPILER_VERSION \"${CELLERATOR_COMPILER_VERSION}\"
#define CELLERATOR_LANGUAGE_REVISION ${CELLERATOR_LANGUAGE_REVISION}
#define CELLERATOR_CEIR_REVISION ${CELLERATOR_CEIR_REVISION}
#define CELLERATOR_HAS_CUDA_BACKEND $<BOOL:${CELLERATOR_HAS_CUDA}>
#define CELLERATOR_INSTALL_RESOURCE_PATH \"${CMAKE_INSTALL_PREFIX}/lib/cellerator\"
")
endfunction()
